In [1]:
#1
import numpy as np

In [3]:
#2
print(np.__version__)
np.show_config()


2.2.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-_1vgc7re/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [4]:
#3
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#4
arr = np.zeros(10)
print(arr.nbytes)

80


In [12]:
#5
%run python -c "import numpy; numpy.info(numpy.add)"

Exception: File `'python'` not found.

In [13]:
#6
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [14]:
#7
arr1 = np.arange(10,50)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [16]:
#8
arr1[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [17]:
#9
arr = np.arange(9).reshape(3, 3)
arr



array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
#10
arr2 = np.nonzero([1,2,0,0,4,0])
print(arr2)

(array([0, 1, 4]),)


In [19]:
#11
matrix = np.eye(3)
print(matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
#12
matrix3 = np.random.random((3,3,3))
matrix3

array([[[0.88534867, 0.0076557 , 0.45996996],
        [0.38445254, 0.93158472, 0.86863582],
        [0.65931103, 0.81420036, 0.69900209]],

       [[0.98523695, 0.76174034, 0.99779974],
        [0.01416071, 0.74946887, 0.15403702],
        [0.08110643, 0.82196576, 0.17001352]],

       [[0.98808858, 0.36698607, 0.24487858],
        [0.47461392, 0.40196799, 0.49369877],
        [0.36634613, 0.24838763, 0.95089615]]])

In [ ]:
#13
matrix10 = np.random.random((10,10))
matrix10min = matrix10.min()
matrix10max = matrix10.max()
print(matrix10min, matrix10max)

0.019800632783276595 0.9991067937930254


In [26]:
#14
vector = np.random.rand(30)
mean_value = np.mean(vector)
print(mean_value)

0.5392645381755546


In [27]:
#15
arr2d = np.ones((10,10))
arr2d[1:-1,1:-1] = 0
arr2d


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
#16
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(arr_with_border)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [3]:
#17 What is the result of the following expression?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)



nan
False
False
nan
True
False


In [4]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

arrd = np.diag([1,2,3,4], k=-1)
print(arrd)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [8]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1

Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [9]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(100, (6,7,8)))

(np.int64(1), np.int64(5), np.int64(4))


In [13]:
#21. Create a checkerboard 8x8 matrix using the tile function
checkerboard = np.array([[0, 1], [1, 0]])
checkerboard_8 = np.tile(checkerboard, (4,4))
print(checkerboard_8)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
#22. Normalize a 5x5 random matrix 
mat5 = np.random.rand(5, 5)
min_v = mat5.min()
max_v = mat5.max()

normalized = (mat5 - min_v) / (max_v - min_v)
print(normalized)

[[0.2527058  0.83838583 0.         0.29096475 0.88913771]
 [0.18322439 0.53288197 0.89244676 0.29923915 0.5840201 ]
 [0.0201296  0.575088   0.4122051  0.01948735 0.9365428 ]
 [0.37975065 1.         0.79604563 0.85005875 0.94540578]
 [0.24894429 0.71907167 0.76601168 0.98568257 0.88845582]]


In [20]:
#23. Create a custom dtype that describes a color as four unsigned bytes
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))]


In [21]:
#24  Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.random.rand(5,3)
b = np.random.rand(3, 2)
c = np.dot(a, b)
print(c)


[[1.0183006  1.05403969]
 [0.41729791 0.43742235]
 [0.97509752 1.00632305]
 [1.13428813 1.19817012]
 [1.42173969 1.50924262]]


In [23]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place.
arr0 = np.arange(10)
arr0[(3 < arr0) & (arr0 <= 8)] *= -1
print(arr0)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


In [24]:
#26. What is the output of the following script
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [25]:
#27. Consider an integer vector Z, which of these expressions are legal?
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [26]:
#28. What are the result of the following expressions?
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\user\AppData\Local\Temp\ipykernel_10520\212840594.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\user\AppData\Local\Temp\ipykernel_10520\212840594.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\user\AppData\Local\Temp\ipykernel_10520\212840594.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [27]:
#29  How to round away from zero a float array ? 
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[  9.   9.   6.  -5.  10.   3.  -6. -10.  -3.  -9.]


In [30]:
#30. How to find common values between two arrays

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
print(np.intersect1d(arr1, arr2))

[3 4 5]
